### ISSUE TITLE
id3.hexpat error for MP3 files: Array expanded past end of the data

### ISSUE THREAD

**Issue by Fruchtzwerg94** [WerWolv/ImHex-Patterns#105]
Opening an MP3 file proposes the [id3.hexpat](https://github.com/WerWolv/ImHex-Patterns/blob/master/patterns/id3.hexpat) to be used which would be indeed really helpful.
Unfortunately, the pattern seems to fail due to some out of bound access. I've tried several random MP3 files on my device, all of them failed with one of the two following errors:
```
error[E0004]: Type error.
  --> <Source Code>:108:38
108 |             char data[parent.size - 1];
                                           ^
                                           Array expanded past end of the data.
```

```
error[E0004]: Type error.
  --> <Source Code>:104:46
104 |             char16 data[(parent.size - 3) / 2];
                                                   ^
                                                   Array expanded past end of the data.
```

Are there any prequisites or details I am missing? Or can this be identified as a bug in the pattern file?

@flimberger : It looks like the pattern was brought in by you. Is the pattern still working like expected for you? Any ideas about the issue?

**Comment by WerWolv** [comment]
Hey
Yeah looks like something's broken with that pattern. Most of the patterns that are available were submitted by users of ImHex so issues like that happen. If you or anybody else has the time and knowledge to look into it, please do and open a PR!

**Comment by flimberger** [comment]
With ImHex version 1.27.1 and my files, the pattern does work as expected for me.

The error seems to be that the calculated size of the ID3.2 frame containing the string data does not match the actual data.
Maybe it is a bug in the calculation of the actual size.

I will look into it.
Having a file with which it does not work would be helping, but I guess sharing it would be impossible because of copyright, correct?

**Comment by Fruchtzwerg94** [comment]
Thanks for having a look into it. Due to copyright, I seems not the best to upload some files here, but I can reference to some [sample MP3 files](https://file-examples.com/index.php/sample-audio-files/sample-mp3-download/) which are showing the issue for me as well.

**Comment by flimberger** [comment]
All those files work fine for me, too. Which version of ImHex do you use?

The error is curious to me, because it occurs in the ID3v2 tag, which is located at the start of the file, so reading the data should not result in out-of-bounds access.

According to the docs, the `[[static]]` attribute causes undefined behaviour, if is used wrong. I couldn't see anything wrong though. @WerWolv would it be possible for you to verify that my use of [FrameId](https://github.com/WerWolv/ImHex-Patterns/blob/master/patterns/id3.hexpat#L111) is valid?

I worked around a limitation of the pattern language, which does not allow `char` data to be compared. The code is a bit hairy, so I am unsure if it is legal.

**Comment by WerWolv** [comment]
It looks like `parent.size` doesn't get read correctly. I'm trying to reproduce it with a smaller pattern right now but I think it's a pattern language bug and not an issue with the pattern itself

**Comment by WerWolv** [comment]
Ah actually never mind, the `SyncSafeInt` [[transform]] function calculation seems to be wrong in some way. I don't know exactly how it should work but I'd look there

**Comment by flimberger** [comment]
The function converts an array of 7-bit integers to a big-endian 28-bit integer.

I assumed C semantics when writing the bit-twiddling code, i.e. 8-bit integers are converted to 32-bit when arithmetic is performed. Is that assumption correct?
Otherwise shifting the byte value left by 21 bits would be invalid.

The strange thing is that for @Fruchtzwerg94 the example files triggered the error, too, although there the `SyncSafeInteger` code only ever uses the least significant byte, so no shift is performed in practice anyway and the transformed value for the `SyncSafeInteger` is just the least significant byte itself.

**Comment by flimberger** [comment]
@Fruchtzwerg94 can you check if this patch fixes your problem?
```
diff --git a/patterns/id3.hexpat b/patterns/id3.hexpat
index 4129395..5d7bb4f 100644
--- a/patterns/id3.hexpat
+++ b/patterns/id3.hexpat
@@ -27,9 +27,8 @@ namespace v2 {
     fn ssi_value(ref SyncSafeInt n) {
         u32 result = 0;
         for (u8 i = 0, i < 4, i = i + 1) {
-            u8 byteval = n.bytes[i] & 0x7F;
-            u8 shift = 7 * (4 - i - 1);
-            result = result | (byteval << shift);
+            u32 byteval = n.bytes[i] & 0x7F;
+            result = result | (byteval << (7 * (3 - i)));
         }
         return result;
     }
```

**Comment by Fruchtzwerg94** [comment]
Unfortunately, no difference after changing the lines. The code behaves exactly like before. I've tried to dig in a little bit deeper, here is what I can see enabling the debug pragma:

The bytes of the first header size struct are marked and detected like expected:
![grafik](https://user-images.githubusercontent.com/29866610/230766599-63e13e1c-44de-42d6-bf60-6b8872ed4f59.png)

Looping through `ssi_value` the log shows:
```
Setting local variable 'byteval' to 84.
Setting local variable 'byteval' to 83.
Setting local variable 'byteval' to 83.
Setting local variable 'byteval' to 69.
```
which is 0x54, 0x53 0x53 0x45. These are exactly the 4 bytes following the originally detected size bytes. So it seems like the calculation is working not wrong referenced bytes. For what ever reason `ssi_value` gets an object with a 4 byte offset passed ... But thats just my first guess.

**Comment by WerWolv** [comment]
Found the issue! Somehow references are broken. If you remove the `ref` from the parameter passed to `ssi_value`, it work fine again

**Comment by WerWolv** [comment]
Latest ImHex commit should fix it. Thanks a lot for investigating!

**Comment by Fruchtzwerg94** [comment]
That was fast :-) ... Thanks for you fast fix and the awesome tool. Keep on going like this!

Merci in die Schweiz,
Philipp
