### ISSUE TITLE
How to represent nested structures that the child may span multiple parent?

### ISSUE THREAD

**Issue by noob-258** [WerWolv/ImHex-Patterns#107]
Hi!
I'm trying to reverse engineer a file format and encountered the following problem. There is a nested structure, the length of the parent structure is fixed, the length of the child structure is variable, the parent structure may contain multiple child structures, and it is also possible that the child structure spans multiple parent structures, like this:
```
struct Parent
{
    u8 header[16];           /* This field should be skipped when child structure span multiple parent structures */
    u8 child_payload[496];
};

struct Child
{
    u16 length;
    u8 secret[length];       /* Here is what I actually want to parse */
};
```

I drew a simple diagram to use as an example:
```
|          |          |          |          |          |
|* |    |   *          *          *  |       *         |
```
- the space between the vertical bars(|) represents a structure.
- the first line indicates that there is a file containing 5 parent structures.
- the second line indicates that these 5 payloads contain 4 child structures, and asterisks(*) indicates that it is the header of the parent structure and needs to be skipped.

**Comment by WerWolv** [comment]
Hey

Take a look at the STL pattern: https://github.com/WerWolv/ImHex-Patterns/blob/master/patterns/stl.hexpat#L43-L51
That format consists of a big list of Triagnle structures that all contain a normal vector plus 3 vertices. The code highlighted at the bottom extracts only the vertices of those structures and puts them in a new array.

If that's enough for you, you're done here. Otherwise, if you want to place patterns in that data, take a look at Custom Sections. 
The documentation isn't very big right now but it basically allows you to define a new buffer, copy data into it and then place patterns in that buffer: https://docs.werwolv.net/pattern-language/core-language/sections

**Comment by noob-258** [comment]
Thank you for your reply!

I have tried both methods you mentioned.

> Take a look at the STL pattern: https://github.com/WerWolv/ImHex-Patterns/blob/master/patterns/stl.hexpat#L43-L51 That format consists of a big list of Triagnle structures that all contain a normal vector plus 3 vertices. The code highlighted at the bottom extracts only the vertices of those structures and puts them in a new array.

How to further reverse engineer the contents of model.vertices? I think this part is the "secret" I mentioned in my question.

> If that's enough for you, you're done here. Otherwise, if you want to place patterns in that data, take a look at Custom Sections. The documentation isn't very big right now but it basically allows you to define a new buffer, copy data into it and then place patterns in that buffer: https://docs.werwolv.net/pattern-language/core-language/sections

The method looks feasible, but my file size may exceed 100MB. When I wrote a demo and tried to run it, it was very slow and crashed several times.

**Comment by paxcut** [comment]
I am having trouble following you example above. You mention nested structures and this usually implies structures used inside other structures, but your example shows structures that use integers.  In addition, when you introfuce your diagram you say that there are five parent structures and  that asterisk mean headers that need to be skipped. Since you show 5 of them, does that mean that all the headers are to be  skipped?
It is very hard to solve problems without references or examples. Maybe you can invent a small test file that can be used to test ideas for patterns that can be shared here. If that's not possible maybe you can give us a little background on the problem or if you don't want to do that maybe you can supply some contextual information   that describes the system you are trying to reverse in very general terms. 
Imhex makes parsing files very easy once you understand how to use the language.  At first I had to read the docs many times and gather information from any place it can be found. After a month or two I feel I still have a lot to learn but everybody seems happy to help so don't hesitate to ask any question you may have.

**Comment by noob-258** [comment]
I apologize for my confusing description above.

I don't know how to describe the many-to-many relationships between these two structures, so this example may look strange. The headers of the parent structures is useless, so all of them should be skipped.

In fact, there is a rather crude solution to this problem. Write a script to remove the first 16 bytes every 512 bytes  (i.e., all the headers of the parent structures), save it as a new file, and then reverse engineer it based on this new file.

**Comment by paxcut** [comment]
You don't really need to edit the file, ImHex makes it easy to skip any number of bytes as you process the file. for example this snippat 
```cpp
if ($ % 512 < 16)
 $ = $ + (16- ($ % 512));
 ```
 will skip any of the first 16 bytes every 512 bytes that you try to read. Even if you can't describe the entire format you may be able to describe a small subset and give some simple examples which don't have to be real files that need reversing but rather files you create to help demonstrate the small subset.

**Comment by paxcut** [comment]
like this/ instead of the full size use a header of say 4 bytes and a payload of 12 bytes
```cpp
struct Parent
{
    u8 header[4];           /* This field should be skipped when child structure span multiple parent structures */
    u8 child_payload[12];
};
```
so an example would be
```
----- header ------     ======================= payload ===========================
0x02 0x55 0x23 0x67     0x74 0x75 0x76 0x77 0x78 0x79 0x7A 0x30 0x31 0x32 0x33 0x34
```
now you can try to explain where the second structure fits into this simplified version

**Comment by noob-258** [comment]
OK, here is a small file of 32 bytes.

```
       0    1    2    3        4    5    6    7    8    9    a    b    c    d    e    f
      ----- header ------     ======================= payload ===========================
0000: 0x01 0x55 0x23 0x67     0x04 0x00 0x76 0x77 0x78 0x79 0x10 0x00 0x31 0x32 0x33 0x34
0010: 0x02 0x65 0x33 0x77     0x84 0x85 0x86 0x87 0x88 0x89 0x8A 0x40 0x41 0x42 0x43 0x44
```
- offset 0x04-0x05 means that the following 4 bytes are first secret.
- offset 0x0a-0x0b means that the following 16 bytes are second secret. As the remaining payload of first parent structure is only 4 bytes, this secret is composed of offset 0x0c-0x0f and 0x14-0x1f.

**Comment by paxcut** [comment]
Ok, I think I understand now. Give me a little time and I'll post a pattern that even if it doesn't work 100% might be enough to get you started.

**Comment by paxcut** [comment]
I expanded the example a little for the case the payload engulfs entire rows.
So data is now:

```
01 55 23 67     04 00 76 77 78 79 12 00 31 32 33 34 
02 65 33 77     84 85 86 87 88 89 8A 40 41 42 43 44 
03 75 43 87     45 46 08 00 31 32 33 34 35 36 37 38
```

This pattern will parse it completely and create 
variables with payload on its name. This was a quick and
dirty job so it has terrible names and it hasn't been tested 
or optimized, but it parses both the example you posted and
the one in this post.

```cpp
#include <std/io.pat>
#include <std/mem.pat>

// Payload can be broken up because of headers
// We call the portion of the payload that occurs 
// before a header the payload head. After it there 
// will be a number (possibly zero) of entire rows
// that has 4 bytes for header and 12 bytes for 
// payload. Those are called header-payload. Then there 
// will be some (possibly empty) payload left. call 
// it payload tail.



struct HeaderPayload  
{
    u8 header[4];
    u8 payload[12];
};

struct Secrets
{
   u16 payloadSize;
   std::print("$ : {}, payloadSize: {}",$,payloadSize);
   if(($ % 16) +payloadSize > 16)
   {
     s32 headerPayloafCount = payloadSize /12;
     std::print("tailCount: {}",headerPayloafCount);
     if(headerPayloafCount <0) headerPayloafCount =0;
     u32 bytesRead=16-($ % 16)+12*headerPayloafCount;
     std::print("bytesRead: {}",bytesRead);
     u8 payloadHead[16-($ % 16)];
     if(headerPayloafCount > 0)
       HeaderPayload headerPayload[headerPayloafCount];
     std::print("secretCount-bytesRead: {}",payloadSize-bytesRead);
     $ += 4;
     u8 payloadTail[payloadSize-bytesRead];
   }
   else
     u8 payload[payloadSize];
};

struct Parser
{
  if ($ % 16 < 4)
     $ = $ + (4- ($ % 16));
   Secrets secrets[while(!std::mem::eof())]; 
 
};

Parser parser @ 0;
```


I can answer any question about how the code works or ways to improve/expand it.

**Comment by noob-258** [comment]
Thank you for your pattern, it has inspired me a lot.

I still have some questions: 
How to further reverse engineer the contents of secret? Is it feasible to merge the separated payload header, body, and tail into one member?
Because the secret is actually a very complex structure(You can think of each secret as an exe file), including many members, some of which may be separated into two or more payloads.

**Comment by paxcut** [comment]
You can do the following:

1. Once you know the total size of the payload you can allocate a separate memory location using what ImHex calls sections. 
2. Write the value of each payload fragment to the allocated section in the right order. Or create separate sections and write each payload sub component to them. You have complete freedom to choose.
3. Create patterns for the payload secrets. This where you figure out the complex inner structure of your payload.
4. place the newly crated structure patterns on the allocated section(s).
5. Inspect the resulting pattern data in the section view that is created separately from the input pattern data but has the same functionality as the input file pattern data view.

It is not very difficult to do these steps except possibly figuring out the structure of your payload secrets. ImHex is very powerful but it is also very new and not complete. As your needs for your projects grow you may run into bugs or non existent  features that you absolutely need (or believe so).  Get involved with the amazing ImHex community by writing feature requests, bug reports, either here or on discord channel. Enhance ImHex by creating plugins or rewriting its source code to fix bugs and submit pull requests to have them incorporated to the main branch. 

The limit to what you can create in order to fully reverse your input files using ImHex exists only in your mind. I would like to welcome you to ImHex and feel free to keep asking questions on this issue or close it and open new ones.

**Comment by noob-258** [comment]
Thanks, I think I can handle it now.

**Comment by paxcut** [comment]
Your welcome. good luck.
