### ISSUE TITLE
std includes not found

### ISSUE THREAD

**Issue by MarkJeronimus** [WerWolv/ImHex-Patterns#136]
I have a standard installation of 1.28.0-1.fc36 (through Fedora's repository)

When I try to write patterns, or copy/paste patterns from this github, it will inevitably give an error on the first `#include <std/...` include, saying "error[M0004]: No such file or directory".

Is that because it's not supported by this old version? Do I have the files but am I missing a setting? Where can I find a newer version that I don't have to compile myself (and isn't an AppImage or whatever)?

**Comment by WerWolv** [comment]
Hi! Yeah v1.28.0 is pretty old but we dropped support for Fedora 36 since it's also no longer supported by the Fedora maintainers. 
If you're lucky you can fix the bug by just going to Help -> Content Store and download the `std` package there from the Libraries tab. Otherwise your options are pretty much to either use the AppImage, the Flatpak, build ImHex yourself or update Fedora to a newer and supported release such as Fedora 37, 38 or rawhide.

If you have more questions about this, please open an issue on the main repository: https://github.com/WerWolv/ImHex
