### ISSUE TITLE
Saving a new file wipes the pattern editor

### ISSUE THREAD

**Issue by LennardF1989** [WerWolv/ImHex-Patterns#148]
I have been using ImHex pretty intensly past few days. Really liking the tool and especially the pattern editor (coming from 010 Editor myself)! However, I have been running into a lot of crashes and nuisances as I was/am reversing a file. I will make a bunch of issues to cover those, this being the first.

If you make a new file, add some stuff in the pattern editor, and then save the file. All the contents of the pattern editor will be lost.

1. File > New File...
2. Type something in Pattern editor
3. File > Save

After saving, the Pattern editor is now empty.

**Comment by paxcut** [comment]
I can confirm this bug on windows. Note that if you use Save As instead of save the bug occurs in a different way. While the pattern editor is not lost, the file does not become the new file that was created and the unnamed file remains. The file was saved though so it needs to be loaded, the pattern data copied and the old file removed.

**Comment by LennardF1989** [comment]
I'll recreate this on the right repository, my bad!
