### ISSUE TITLE
pe.hexpat does not parse correctly the reloc section

### ISSUE THREAD

**Issue by g4ngli0s** [WerWolv/ImHex-Patterns#211]
I am using the amazing ImHex program to learn reversing and I realize that the PE pattern is not parsing the .reloc table correctly. I have no idea about "Pattern language" but if you simply load the pattern in the classic calc.exe from windows you can realize that there are not 5 blocks of .reloc, there are only 2 blocks. 

![image](https://github.com/WerWolv/ImHex-Patterns/assets/24944277/35b98a72-1403-4c57-9558-f4c6a7529f79)

As you can see in the editor, the pattern does not show the different RVA addresses (2 bytes) where to change the delta:

![image](https://github.com/WerWolv/ImHex-Patterns/assets/24944277/cdefb462-253a-42ad-bdb2-e9bc47a852ac)

This pattern should be something like this:

![image](https://github.com/WerWolv/ImHex-Patterns/assets/24944277/c889ab98-c4d8-4ffa-ab12-50f4a59c7c7e)

I guess that there is something wrong with this code:

```
struct BaseRelocationTable {
	BaseRelocationBlock baseRelocationBlocks[while($ < addressof(this) + coffHeader.optionalHeader.directories[5].size)];
};
```

Sorry about my English, I hope you can see what I mean.

Regards and thanks!

**Comment by WerWolv** [comment]
Hi, thank you! The pattern was made by @gmestanley, maybe they can help?

**Comment by gmestanley** [comment]
Hi! Yes, I made this. I submitted most of my additions to pe.hexpat basing myself on [Microsoft's own documentation of the format](https://web.archive.org/web/20220630194400/https://docs.microsoft.com/en-us/windows/win32/debug/pe-format). I didn't catch [the part where it says the table can have "**any number** of field entries"](https://web.archive.org/web/20220630194400/https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#base-relocation-block) and just assumed it was only one instead of being an array.
I'll provide a fix soon.

**Comment by gmestanley** [comment]
Oh oops, saw that you provided a pull request a day after the comment, sorry.
