### ISSUE TITLE
obscure pattern welcome?

### ISSUE THREAD

**Issue by ccoenen** [WerWolv/ImHex-Patterns#234]
I own a device that's pretty old and no longer manufactured. It has a pretty simple file format that I created a pattern for to learn the pattern language. Should I contribute it? I doubt that it has *practical* use, but it is a very simple format and might serve as an example. The whole file is an array of the same `struct` and it also has a few bitfields.

**Comment by WerWolv** [comment]
Hey!
Generally everything is welcome as long as the pattern _might_ have any use for someone else.

Obscure formats that are only useful in very specific cases are therefor completely fine, even if they might only help very few people.
Formats that are only used internally in e.g the company you work for are the exception here since these most likely shouldn't be made public anyways and also probably would only help you and maybe your work colleagues.

For your case, I think definitely go for it :)
