### ISSUE TITLE
pattern: FBX - NodeRecord subtrees not working correctly

### ISSUE THREAD

**Issue by Hikodroid** [WerWolv/ImHex-Patterns#275]
This is a follow up to the comment I made in my pull request: https://github.com/WerWolv/ImHex-Patterns/pull/271

I added a print statement to Blenders FBX exporter and it returned this - I formatted and shortened the output:

FBXElem(id=b'', props=[], props_type=bytearray(b''), elems=[
	FBXElem(id=b'FBXHeaderExtension', props=[], props_type=bytearray(b''), elems=[
		FBXElem(id=b'FBXHeaderVersion', props=[1003], props_type=bytearray(b'I'), elems=[]), 
		FBXElem(id=b'FBXVersion', props=[7400], props_type=bytearray(b'I'), elems=[]), 
		FBXElem(id=b'EncryptionType', props=[0], props_type=bytearray(b'I'), elems=[]), 
		FBXElem(id=b'CreationTimeStamp', props=[], props_type=bytearray(b''), elems=[
			FBXElem(id=b'Version', props=[1000], props_type=bytearray(b'I'), elems=[]), 
			FBXElem(id=b'Year', props=[2024], props_type=bytearray(b'I'), elems=[]), 
			FBXElem(id=b'Month', props=[7], props_type=bytearray(b'I'), elems=[]), 
			FBXElem(id=b'Day', props=[2], props_type=bytearray(b'I'), elems=[]), 
			FBXElem(id=b'Hour', props=[18], props_type=bytearray(b'I'), elems=[]), 
			FBXElem(id=b'Minute', props=[41], props_type=bytearray(b'I'), elems=[]), 
			FBXElem(id=b'Second', props=[18], props_type=bytearray(b'I'), elems=[]), 
			FBXElem(id=b'Millisecond', props=[922], props_type=bytearray(b'I'), elems=[])
		]), .....

This showed me that "Version" is supposed to be a child node of "CreationTimeStamp" but my hexpat does not do that, it is just another NodeRecord that follows "CreationTimeStamp". I have no idea why it does that. I closed my pr because I can't figure this one out. Sorry for the hassle that this probably causes.

**Comment by WerWolv** [comment]
Ah sorry, I just ran the pattern on your test file and it ran fine. Sorry for jumping the gun a bit too quickly.

Would you like me to remove your pattern again? Or do you think it could still be useful for somebody even if it's not 100% correct?

**Comment by paxcut** [comment]
I looked at the code posted in the PR assuming that is the latest code, but the PR is closed and you seem to be making revisions so my comments may not apply to the latest code.
Having said that and based on the code I saw and the comments you are posting, I suspect you are trying to uses recursive templated patterns which the pattern language does not currently support due to implementation limitations. Previously the attempted use of such constructs resulted in ImHex crashing so to avoid that the code only generates one recursion level and then it stops . It doesn't warn you of the danger and it doesn't clarify the action that was taken so at first it looks like it worked but when you look closer you find that something is wrong. I believe that their implementation is somewhat necessary and if they can't be made to work, then there should be better information supplied than what it currently does.

 I know how to deal with the case of non-type template parameters using the parent keyword. For the type template arguments the only solution I can think of is template instantiation which is what you are currently using based on your comments. I just wanted to answer the questions posted in your last post. Not the best source of information, but there are discussions about this topic in the Discord channels if you are interested in learning more about the issue and that is probably the only place.

**Comment by paxcut** [comment]
I can see how it can be confusing unless you knew what it was doing which is what motivated me to post. Closing it as "not currently planned for" is what I would do, but feel free  to do otherwise. My impression is that a proper fix requires major restructuring of how recursive patterns are implemented so it may be a while before this can be cleared as resolved.
