### ISSUE TITLE
Wasm Pattern

### ISSUE THREAD

**Issue by spotandjake** [WerWolv/ImHex-Patterns#75]
Hi i was wondering if there was any pattern made for webassembly?

**Comment by WerWolv** [comment]
Hey
I was working on one a while ago and I thought I uploaded it but apparently not. Also can't find it anywhere anymore, sorry

**Comment by spotandjake** [comment]
Thankyou Very much.

Question on weather the issue should be left open though it would be relavant to the repo right and would make sense to add eventually?

Wondering if this should be left open as a feature request.

**Comment by cyberixae** [comment]
> Nevermind, I found it! [wasm.txt](https://github.com/WerWolv/ImHex-Patterns/files/10423049/wasm.txt)
> 
> It's nowhere near done yet but it parses at least some of the different sections

Is there a chance that this could be included in a future release? It seems useful in it's current incomplete form. However, setting it up is currently a bit of a hassle, since one needs to first find this issue, download and rename the file, place it in the pattern directory directory, load it manually, and possibly even fix a duplicate import error to make it work.

**Comment by WerWolv** [comment]
I might have a look at it again in the future. But I rather not include my own patterns usually that are as incomplete as this. I would accept PRs though that improve upon it, using my pattern here as a base
